version: '2'
services:
    odoo:
        image: odoo:12.0
        depends_on:
            - database
        ports:
            - 8069:8069
        environment:
            - HOST=database
            - USER=odoo
            - PASSWORD=odoo
        working_dir: /mnt/extra-addons
        volumes:
            - odoo-web-data:/var/lib/odoo
            - ./config:/etc/odoo
            - ./src:/mnt/extra-addons

    database:
        image: postgres:10
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
    odoo-web-data:
    odoo-db-data: